# Pinned shadercross 1ff05bec overrides the parent's deployment target.
# Preserve its standalone default while honoring the application's macOS floor.
function(playground_patch_shadercross_macos source_dir)
    set(source "${source_dir}/CMakeLists.txt")
    set(original_sha256 5971a8a081dc9cdd2501a82d6b1f0dcb45a8de6156a908ca7f963d3b3ef53ee9)
    set(original "\tset(CMAKE_OSX_DEPLOYMENT_TARGET 11.0)")
    set(replacement "\tif(NOT CMAKE_OSX_DEPLOYMENT_TARGET)\n\t\tset(CMAKE_OSX_DEPLOYMENT_TARGET 11.0)\n\tendif()")
    file(READ "${source}" content)
    string(FIND "${content}" "${replacement}" patched)
    if(NOT patched EQUAL -1)
        string(REPLACE "${replacement}" "${original}" unpatched "${content}")
        string(SHA256 actual_sha256 "${unpatched}")
    else()
        file(SHA256 "${source}" actual_sha256)
    endif()
    if(NOT actual_sha256 STREQUAL original_sha256)
        message(FATAL_ERROR "shadercross deployment patch source mismatch; review the pinned revision")
    endif()
    if(patched EQUAL -1)
        string(REPLACE "${original}" "${replacement}" content "${content}")
        file(WRITE "${source}" "${content}")
    endif()
endfunction()
