# GUIDE's C++ blocks form one additive translation unit, not an executable.
file(READ "${INPUT}" guide)
string(REPLACE "\r\n" "\n" guide "${guide}")
set(source "// Generated from docs/ui/GUIDE.md; do not edit.\n")
set(count 0)
while(TRUE)
    string(FIND "${guide}" "```cpp\n" begin)
    if(begin EQUAL -1)
        break()
    endif()
    math(EXPR begin "${begin} + 7")
    string(SUBSTRING "${guide}" ${begin} -1 guide)
    string(FIND "${guide}" "\n```" end)
    if(end EQUAL -1)
        message(FATAL_ERROR "Unclosed C++ fence in ${INPUT}")
    endif()
    string(SUBSTRING "${guide}" 0 ${end} block)
    string(APPEND source "${block}\n\n")
    math(EXPR count "${count} + 1")
    math(EXPR end "${end} + 4")
    string(SUBSTRING "${guide}" ${end} -1 guide)
endwhile()
if(count EQUAL 0)
    message(FATAL_ERROR "No C++ blocks found in ${INPUT}")
endif()
file(WRITE "${OUTPUT}" "${source}")
