# Run after CMake generation, including when an individual project target builds.
# No Python, platform-specific paths, or hand-maintained dependency includes.
if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED BUILD_ROOT)
    message(FATAL_ERROR "PROJECT_ROOT and BUILD_ROOT are required")
endif()
file(READ "${BUILD_ROOT}/compile_commands.json" database)
string(JSON count LENGTH "${database}")
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
    string(JSON source GET "${database}" ${index} file)
    cmake_path(NORMAL_PATH source)
    string(SHA256 key "${source}")
    set(command_index_${key} ${index})
    if(source STREQUAL "${PROJECT_ROOT}/src/main.cpp")
        set(fallback ${index})
    endif()
endforeach()
if(NOT DEFINED fallback)
    message(FATAL_ERROR "No application command found for editor header entries")
endif()

function(json_quote output value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

string(REGEX REPLACE "[ \t\r\n]*\\][ \t\r\n]*$" "" editor "${database}")
file(GLOB_RECURSE headers LIST_DIRECTORIES false
    "${PROJECT_ROOT}/include/*.hpp" "${PROJECT_ROOT}/include/*.h"
    "${PROJECT_ROOT}/src/*.hpp" "${PROJECT_ROOT}/src/*.h")
foreach(header IN LISTS headers)
    string(REPLACE "${PROJECT_ROOT}/include/" "${PROJECT_ROOT}/src/" owner "${header}")
    string(REGEX REPLACE "\\.h(pp)?$" ".cpp" owner "${owner}")
    string(SHA256 key "${owner}")
    set(index ${fallback})
    if(DEFINED command_index_${key})
        set(index ${command_index_${key}})
    endif()
    string(JSON entry GET "${database}" ${index})
    string(JSON source GET "${entry}" file)
    string(JSON command GET "${entry}" command)
    # CMake uses native separators in MSVC commands and forward slashes in file.
    string(REPLACE "\\" "/" normalized "${source}")
    string(REPLACE "/" "\\" native "${normalized}")
    # Replace quoted inputs before unquoted ones, then insert one quoted path.
    # A new header may contain spaces even when its owning .cpp does not.
    set(input_token "__PLAYGROUND_EDITOR_INPUT__")
    string(REPLACE "\"${native}\"" "${input_token}" command "${command}")
    string(REPLACE "\"${normalized}\"" "${input_token}" command "${command}")
    string(REPLACE "${native}" "${input_token}" command "${command}")
    string(REPLACE "${normalized}" "${input_token}" command "${command}")
    if(NOT command MATCHES "${input_token}")
        message(FATAL_ERROR "Cannot locate source argument for ${header}")
    endif()
    string(REPLACE "${input_token}" "\"${header}\"" command "${command}")
    json_quote(file_json "${header}")
    json_quote(command_json "${command}")
    string(JSON entry SET "${entry}" file "${file_json}")
    string(JSON entry SET "${entry}" command "${command_json}")
    string(JSON unused ERROR_VARIABLE missing_output GET "${entry}" output)
    if(NOT missing_output)
        string(JSON entry REMOVE "${entry}" output)
    endif()
    string(APPEND editor ",\n${entry}")
endforeach()
string(APPEND editor "\n]\n")
set(destination "${PROJECT_ROOT}/compile_commands.json")
# Preserve timestamps when unchanged so clangd does not rebuild unnecessarily.
set(previous "")
if(EXISTS "${destination}")
    file(READ "${destination}" previous)
endif()
if(NOT editor STREQUAL previous)
    # Publish a complete file so an active clangd cannot read half-written JSON.
    file(WRITE "${BUILD_ROOT}/editor_compile_commands.json" "${editor}")
    file(RENAME "${BUILD_ROOT}/editor_compile_commands.json" "${destination}")
endif()
